import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { SetlistEntryData } from '../types/setlist';

export const useSetlistEntryActions = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'processing' | 'done' | 'error'>('idle');

  // Add the updateStatistics function - runs in background and reports status
  const updateStatistics = async () => {
    try {
      const { data, error } = await supabase
        .rpc('update_all_setlist_entries');
      
      if (error) {
        setSaveStatus('error');
        return false;
      } else {
        setSaveStatus('done');
        return true;
      }
    } catch (error) {
      setSaveStatus('error');
      return false;
    }
  };

  // Save guest associations for a setlist entry
  const saveGuestAssociations = async (entryId: string, selectedGuestIds: string[]) => {
    try {
      // Fetch current associations
      const { data: currentAssociations, error: fetchError } = await supabase
        .from('setlist_entry_guests')
        .select('guest_id')
        .eq('setlist_entry_id', entryId);
      
      if (fetchError) throw fetchError;
      
      const currentGuestIds = currentAssociations?.map(item => item.guest_id) || [];
      
      // Determine which guests to add and which to remove
      const guestsToAdd = selectedGuestIds.filter(id => !currentGuestIds.includes(id));
      const guestsToRemove = currentGuestIds.filter(id => !selectedGuestIds.includes(id));
      
      // Process removals if needed
      if (guestsToRemove.length > 0) {
        const { error: deleteError } = await supabase
          .from('setlist_entry_guests')
          .delete()
          .eq('setlist_entry_id', entryId)
          .in('guest_id', guestsToRemove);
        
        if (deleteError) throw deleteError;
      }
      
      // Process additions if needed
      if (guestsToAdd.length > 0) {
        const guestAssociations = guestsToAdd.map(guestId => ({
          setlist_entry_id: entryId,
          guest_id: guestId
        }));
        
        // Insert one at a time to handle potential issues with individual records
        for (const association of guestAssociations) {
          const { error: insertError } = await supabase
            .from('setlist_entry_guests')
            .insert(association)
            .select();
          
          if (insertError) {
            // If we hit a unique constraint error, just skip and continue
            if (insertError.code !== '23505') { // PostgreSQL unique violation code
              throw insertError;
            }
          }
        }
      }
      
    } catch (error) {
      throw error;
    }
  };

  const saveEntry = async (
    editedEntry: SetlistEntryData,
    selectedGuestIds: string[],
    selectedNewSongOption: string,
    isNewEntry: boolean,
    onSave: () => void,
    onSaveStatusUpdate: (status: 'idle' | 'processing' | 'done' | 'error') => void
  ) => {
    // Check if required fields are filled for new entries
    if (isNewEntry) {
      if (!editedEntry.entry_set || !editedEntry.entry_song) {
        alert('Please fill in all required fields (Set and Song are required)');
        return;
      }
    }

    // Set initial status
    setSaveStatus('processing');
    onSaveStatusUpdate('processing');
    
    try {
      // Create a copy of editedEntry with empty strings and "--" converted to null
      const entryToSave = {
        ...editedEntry,
        entry_set: editedEntry.entry_set === "--" ? null : editedEntry.entry_set,
        entry_setnum: editedEntry.entry_setnum === "--" ? null : (typeof editedEntry.entry_setnum === 'string' && editedEntry.entry_setnum === "--" ? null : editedEntry.entry_setnum),
        entry_song: editedEntry.entry_song === "--" ? null : editedEntry.entry_song,
        entry_short: editedEntry.entry_short === "" || editedEntry.entry_short === "--" ? null : editedEntry.entry_short,
        entry_segue: editedEntry.entry_segue === "" || editedEntry.entry_segue === "--" ? null : editedEntry.entry_segue,
        entry_length: editedEntry.entry_length === "" ? null : editedEntry.entry_length,
        entry_placement: editedEntry.entry_placement === "" || editedEntry.entry_placement === "--" ? null : editedEntry.entry_placement,
        entry_coachnotes: editedEntry.entry_coachnotes === "" ? null : editedEntry.entry_coachnotes,
        entry_new: selectedNewSongOption === "N/A" ? "FALSE" : selectedNewSongOption
      };
      
      let savedEntryId: string;
      
      if (isNewEntry) {
        // Insert new entry - Omit entry_id as it will be generated by the database
        
        // Create a data object without the entry_id and entry_setorder for insertion
        const insertData: any = {
          entry_set: entryToSave.entry_set,
          entry_setnum: entryToSave.entry_setnum,
          entry_song: entryToSave.entry_song,
          entry_show: entryToSave.entry_show,
          entry_new: entryToSave.entry_new
        };
        
        // Add optional fields only if they have values
        if (entryToSave.entry_short) insertData['entry_short'] = entryToSave.entry_short;
        if (entryToSave.entry_segue) insertData['entry_segue'] = entryToSave.entry_segue;
        if (entryToSave.entry_length) insertData['entry_length'] = entryToSave.entry_length;
        if (entryToSave.entry_placement) insertData['entry_placement'] = entryToSave.entry_placement;
        if (entryToSave.entry_coachnotes) insertData['entry_coachnotes'] = entryToSave.entry_coachnotes;
        
        const { data, error } = await supabase
          .from('setlist_entries')
          .insert(insertData)
          .select();
        
        if (error) {
          alert(`Error creating entry: ${error.message}`);
          setSaveStatus('error');
          onSaveStatusUpdate('error');
          throw error;
        }
        
        // Get the new entry ID
        if (data && data.length > 0) {
          savedEntryId = data[0].entry_id;
          
          // Save guest associations if any are selected
          if (selectedGuestIds.length > 0) {
            await saveGuestAssociations(savedEntryId, selectedGuestIds);
          }
        }
        
        // Refresh table data immediately after insert and guest associations
        onSave(); // Trigger refetch of entries
      } else {
        // Update existing entry
        
        const { error } = await supabase
          .from('setlist_entries')
          .update({
            entry_set: entryToSave.entry_set,
            entry_setnum: entryToSave.entry_setnum,
            entry_song: entryToSave.entry_song,
            entry_short: entryToSave.entry_short,
            entry_segue: entryToSave.entry_segue,
            entry_length: entryToSave.entry_length,
            entry_placement: entryToSave.entry_placement,
            entry_coachnotes: entryToSave.entry_coachnotes,
            entry_new: entryToSave.entry_new
          })
          .eq('entry_id', entryToSave.entry_id);
        
        if (error) {
          alert(`Error updating entry: ${error.message}`);
          setSaveStatus('error');
          onSaveStatusUpdate('error');
          throw error;
        }
        
        // Save guest associations
        await saveGuestAssociations(entryToSave.entry_id, selectedGuestIds);
        
        // Refresh table data immediately after update and guest associations
        onSave(); // Trigger refetch of entries
      }
      
      // Update statistics in background (RPC call)
      await updateStatistics();
      
      // Set success status after everything is complete
      setSaveStatus('done');
      onSaveStatusUpdate('done');
    } catch (error) {
      setSaveStatus('error');
      onSaveStatusUpdate('error');
    } finally {
      setIsSubmitting(false);
    }
  };

  const deleteEntry = async (
    entryId: string,
    onSave: () => void,
    onClose: () => void,
    onSaveStatusUpdate: (status: 'idle' | 'processing' | 'done' | 'error') => void
  ) => {
    setIsSubmitting(true);
    setSaveStatus('processing');
    onSaveStatusUpdate('processing');
    
    try {
      const { error } = await supabase
        .from('setlist_entries')
        .delete()
        .eq('entry_id', entryId);
      
      if (error) {
        alert(`Error deleting entry: ${error.message}`);
        setSaveStatus('error');
        onSaveStatusUpdate('error');
      } else {
        await updateStatistics();
        onSave();
        onClose();
      }
    } catch (error) {
      setSaveStatus('error');
      onSaveStatusUpdate('error');
    } finally {
      setIsSubmitting(false);
    }
  };

  return {
    isSubmitting,
    saveStatus,
    saveEntry,
    deleteEntry
  };
};
